general:
  verbose: true
  collectTelemetryData: false
  
stages:
  UploadSOL:
    changeManagement:
      type: 'SOLMAN'
      credentialsId: 'SOLMAN_CREDENTIALS_ID'
      endpoint: 'https://wdflbmd21817.wdf.sap.corp:50001/sap/opu/odata/SAP/AI_CRM_GW_CM_CI_SRV'
      solman:
        docker:
          image: 'rstengel/cm-client-sap-cert'
    applicationName: 'RDSTR_SOL_APP'
    applicationId: 'HCP'
    abapPackage: 'RDSPACK'
    
  UploadCTS:
    changeManagement:
      type: 'CTS'
      credentialsId: 'CTS_CREDENTIALS_ID'
#      endpoint: 'http://wdflbmd16301.wdf.sap.corp:8000/sap/opu/odata/SAP/SCTS_CLOUD_API_ODATA_SRV'
      endpoint: 'http://wdflbmd16301.wdf.sap.corp:8000'
      client: '001'
    applicationName: 'RDSTR_CTS_APP'
    abapPackage: 'RDSPACK'
    
steps:
  mtaBuild:
    dockerImage: 'devxci/mbtci-alpine'
    
  cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    dockerImage: 'ppiper/cf-cli'
    cloudFoundry:
      org: 'pipertest'
      space: 'J333'
      credentialsId: 'CF_CREDENTIALSID'
      
  isChangeInDevelopment:
    dockerImage: 'rstengel/cm-client-sap-cert'
    
  checkChangeInDevelopment:
    changeManagement:
      type: 'SOLMAN'
      solman:
        docker:
          image: 'rstengel/cm-client-sap-cert'
    
  transportRequestUploadCTS:
    changeManagement:
      credentialsId: 'CTS_CREDENTIALS_ID'
      endpoint: 'http://wdflbmd16301.wdf.sap.corp:8000/sap/opu/odata/SAP/SCTS_CLOUD_API_ODATA_SRV'
    applicationName: 'RDSTR_CTS_APP'
    abapPackage: 'RDSPACK'
#    dockerImage: 'rstengel/fiori'
#    npmInstallOpts: []
#    deployToolDependencies: []

  transportRequestUploadRFC:
    changeManagement:
      credentialsId: 'RFC_CREDENTIALS_ID'
      endpoint: 'wdflbmd16301.wdf.sap.corp'
    dockerImage: 'rstengel/node-rfc'
    
  transportRequestUploadSOLMAN:
    dockerImage: 'rstengel/cm-client-sap-cert'
    
  xtransportRequestUploadFile:
    changeManagement:
      type: 'CTS'
      credentialsId: 'CTS_CREDENTIALS_ID'
#      endpoint: 'http://wdflbmd16301.wdf.sap.corp:8000/sap/opu/odata/SAP/SCTS_CLOUD_API_ODATA_SRV'
      client: '001'
#      cts:
#        nodeDocker:
#          image: 'rstengel/fiori'
#          pullImage: true
#        npmInstallOpts: []
#        deployToolDependencies: []
    applicationName: 'RDSTR_CTS_APP'
    abapPackage: 'RDSPACK'
